analyze_job_task:
  description: >
    Analyze the {job_url} description and score the candidate's fit based on their resume at {resume_path}.
    Output structured JSON data.

    1. Extract Requirements:
       - Technical skills (required vs nice-to-have)
       - Soft skills
       - Experience levels
       - Education requirements
       - Industry knowledge

    2. Score Technical Skills (35%):
       - Match Level (0-1)
       - Years Experience
       - Context Score
       - Weighted average

    3. Score Soft Skills (20%):
       - Identify from resume
       - Compare to requirements
       - Assess context

    4. Score Experience (25%):
       - Years of relevant experience
       - Role similarity
       - Industry relevance
       - Project complexity

    5. Score Education (10%):
       - Degree match
       - Field relevance
       - Certifications

    6. Score Industry Knowledge (10%):
       - Industry experience
       - Domain expertise
       - Achievements

    7. Calculate Overall Score:
       - Weighted average
       - List strengths and gaps
       - Explain scoring

  expected_output: >
    Structured JSON data per JobRequirements model schema.
  agent: job_analyzer

optimize_resume_task:
  description: >
    Review the resume at {resume_path} against the job analysis and create optimization suggestions.
    Output structured JSON data.

    1. Content Analysis:
       - Compare with job requirements
       - Identify missing keywords/skills
       - Analyze achievements
       - Check ATS compatibility

    2. Structure Review:
       - Evaluate section organization
       - Check formatting
       - Assess hierarchy
       - Verify contact details

    3. Generate Suggestions:
       - Content improvements (before/after)
       - Skills to highlight
       - Achievements to add/modify
       - ATS recommendations

  expected_output: >
    Structured JSON data per ResumeOptimization model schema.
  agent: resume_analyzer
  context: [analyze_job_task]

research_company_task:
  description: >
    Research {company_name} for 2025 and prepare a comprehensive analysis.
    Output structured JSON data.

    1. Company Overview:
       - Recent developments
       - Culture and values
       - Market position
       - Growth trajectory

    2. Interview Preparation:
       - Common questions
       - Company-specific topics
       - Recent projects
       - Challenges/opportunities

  expected_output: >
    Structured JSON data per CompanyResearch model schema.
  agent: company_researcher
  context: [analyze_job_task, optimize_resume_task]

generate_resume_task:
  description: >
    Using optimization suggestions and job analysis, create a polished markdown resume from {resume_path}.
    Avoid markdown code blocks (```).

    1. Content Integration:
       - Apply optimization suggestions
       - Add keywords/skills
       - Enhance achievements
       - Ensure ATS compatibility

    2. Formatting:
       - Use markdown headers (#, ##, ###)
       - Consistent styling
       - Clear hierarchy
       - Effective bullet points

    3. Documentation:
       - Track changes
       - Note preserved elements
       - Explain optimizations

  expected_output: >
    An ATS-friendly markdown resume incorporating all optimizations, with documented changes.
  agent: resume_writer
  context: [optimize_resume_task, analyze_job_task, research_company_task]

generate_report_task:
  description: >
    Create an executive summary report from previous steps’ data.
    Format in markdown without code blocks (```).

    1. Data Integration:
       - Job analysis scores
       - Resume optimization details
       - Company research
       - Resume changes

    2. Report Sections:
       ## Executive Summary
       - Match score, quick wins
       - Strengths, improvement areas
       - Action items

       ## Job Fit Analysis
       - Score breakdown
       - Skills assessment
       - Experience alignment

       ## Optimization Overview
       - Resume improvements
       - ATS results
       - Impact metrics

       ## Company Insights
       - Culture fit
       - Interview tips
       - Talking points

       ## Next Steps
       - Action items
       - Skill development
       - Application strategy

    3. Formatting:
       - Markdown headers
       - Emojis for clarity
       - Tables where appropriate
       - Bullet points

  expected_output: >
    A comprehensive markdown report with actionable insights.
  agent: report_generator
  context: [analyze_job_task, optimize_resume_task, research_company_task]